import { createFactory } from 'react'

import MeeKanic from 'clients/MeeKanic'
import Kritter from 'clients/Kritter'
import PickAFlick from 'clients/PickAFlick'
import QuickNote from 'clients/QuickNote'
import ApiSupply from 'clients/ApiSupply'

export default [{
        description: 'Imagine being able to lookup, order, and recieve detailed instructions on how to fix your car right from your phone.',
        duration: '2017-2017',
        name: 'MeeKanic',
        // location: '',
        logo: require('img/meekanic/meekanic1.jpg'),
        loadComponent: createFactory(MeeKanic),
        order: 0,
        properties: { className: 'black' },
        slug: 'meekanic',
        // appstore: 'https://itunes.apple.com/app/id1246860040',
        // playstore: 'https://play.google.com/store/apps/details?id=com.recipelist',
        role: 'Creator',
        scope: 'Web, Mobile',
        stack: 'React-Native, React, Firebase',
        website: 'https://mee-kanic.com',
        github: 'https://github.com/GavinThomas1192/motoMechanicMeeKanic',
    },
    {
        description: 'In a world of negativity Kritter gives animals lovers a place to have a laugh.',
        duration: '2017-2017',
        name: 'Kritter',
        location: 'Seattle, WA',
        logo: require('img/kritter/kritter4.jpg'),
        loadComponent: createFactory(Kritter),
        order: 1,
        properties: { className: 'black' },
        slug: 'kritter',
        // appstore: 'https://itunes.apple.com/us/app/id1196979318',
        // playstore: 'https://play.google.com/store/apps/details?id=com.jomoapp.jomo',
        role: 'Developer',
        scope: 'Web, Mobile',
        stack: 'React, Node.js, MongoDB',
        website: 'https://kritter.club',
        github: 'https://github.com/arn1313/kritter-frontend',
    },
    {
        description: 'Finally, a solution to the "What do you want to watch" dilemma, Pick-A-Flick',
        duration: '2017-2017',
        name: 'Pick-A-Flick',
        location: 'Seattle, WA',
        logo: require('img/pickaflick/pick1.jpg'),
        loadComponent: createFactory(PickAFlick),
        order: 2,
        properties: { className: 'black' },
        slug: 'pickAFlick',
        // appstore:
        // 'https://itunes.apple.com/us/app/taplet-hd-photos-from-iphone-gopro-or-snapchat/id670785096?mt=8',
        // playstore: '',
        role: 'Developer',
        scope: 'Web, API',
        stack: 'Javascript, Node.js, API',
        website: 'https://pic-a-flic.herokuapp.com/',
        github: 'https://github.com/esack7/301-Final_Project',
    },
    {
        description: 'QuickNote is the most efficient way to take notes while web browsing',
        duration: '2017',
        name: 'QuickNote',
        location: 'Seattle, WA',
        logo: require('img/quicknote/quicknote1.jpg'),
        loadComponent: createFactory(QuickNote),
        order: 3,
        properties: { className: 'black' },
        slug: 'quicknote',
        // appstore: 'https://itunes.apple.com/us/app/blipme/id981886073?mt=8',
        playstore: 'https://chrome.google.com/webstore/detail/quicknote/dcpdoelecfeoaagkleajgaeedkdaibad',
        role: 'Developer',
        scope: 'Web Browsing',
        stack: 'Chrome, Extention, Webpack, React',
        website: 'https://chrome.google.com/webstore/detail/quicknote/dcpdoelecfeoaagkleajgaeedkdaibad',
        github: 'https://https://github.com/GavinThomas1192/firstChromeExt',
    },
    {
        description: 'API-Supply provides developers a mainstreamed source to get important information about popular APIs for their project',
        duration: '2017-2017',
        name: 'API-Supply',
        location: 'Seattle, WA',
        logo: require('img/apisupply/api3.jpg'),
        loadComponent: createFactory(ApiSupply),
        order: 4,
        properties: { className: 'black' },
        slug: 'apisupply',
        // appstore: '',
        // playstore: '',
        role: 'Developer',
        scope: 'web, Backend',
        stack: 'MongoDB, RESTful, Node.js',
        website: 'gavinthomas1192.github.io/API-SupplyFront/',
        github: 'github.com/Lonewalker72/API_Supply/',
    },
    // client: {
    //   description: '',
    //   duration: '',
    //   name: '',
    //   order: '',
    //   properties: null,
    //   slug: '',
    //   appstore: '',
    //   playstore: '',
    //   role: '',
    //   scope: '',
    //   stack: '',
    //   website: '',
    // },
]

export const moreWork = [
    // {
    //   img: 'gener8tor',
    //   href: 'http://gener8tor.com',
    // },
    // {
    //   img: 'optyn',
    //   href: 'https://optyn.com/',
    // },
    // {
    //   img: 'wemontage',
    //   href: 'http://wemontage.com',
    // },
    // {
    //   img: 'beekeeper',
    //   href: 'http://beekeeperdata.com',
    // },
    // {
    //   img: 'joyspace',
    //   href: 'https://angel.co/taplet-1',
    // },
    // {
    //   img: 'poparazzi',
    //   // href: '',
    // },
    // {
    //   img: 'sunsportmarine',
    //   // href: '',
    // },
    // {
    //   img: 'kioh',
    //   // href: '',
    // },
]